repos:
  - repo: https://github.com/botsandus/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-json
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--no-sort-keys"
          - "--indent=4"

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
      - id: ruff-format

  # Ruff doesn't implement no-member check yet
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.1.0
    hooks:
    - id: pylint
      args:
        [
          "--disable=all",
          "--enable=E1101"  # no-member
        ]
